# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20, unique=True)),
                ('prestataire', models.CharField(max_length=150)),
                ('client', models.CharField(max_length=150)),
                ('professionnel', models.CharField(max_length=150)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
            ],
        ),
    ]
