# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSafeDeal_NoAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='key',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
