# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSafeDeal_NoAdmin', '0002_customuser_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='isValidate_Client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='isValidate_Prestataire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='isValidate_Professionnel',
            field=models.BooleanField(default=False),
        ),
    ]
