# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSafeDeal_NoAdmin', '0004_auto_20180111_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='projet',
            name='prestataire',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
