# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSafeDeal_NoAdmin', '0005_auto_20180115_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='description',
        ),
        migrations.RemoveField(
            model_name='files',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='files',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
