# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSafeDeal_NoAdmin', '0008_files_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
