# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSafeDeal_NoAdmin', '0009_auto_20180116_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.AddField(
            model_name='files',
            name='typeName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
